### ISSUE TITLE
Hub connect request timed out

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/datacontainer#20]
I get time out. 

```
(py34)ubuntu@ipengine-100:~$ python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Oct 19 2015, 21:52:17) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ipyparallel import Client
>>> rc = Client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda/envs/py34/lib/python3.4/site-packages/ipyparallel/client/client.py", line 469, in __init__
    self._connect(sshserver, ssh_kwargs, timeout)
  File "/home/ubuntu/anaconda/envs/py34/lib/python3.4/site-packages/ipyparallel/client/client.py", line 589, in _connect
    raise error.TimeoutError("Hub connection request timed out")
ipyparallel.error.TimeoutError: Hub connection request timed out
```

Why is it caused? What can I do when this occurs?

**Comment by ajelenak-thg** [comment]
Can you list all the steps before this happened?

**Comment by hyoklee** [comment]
I'm just following the [instruction](https://github.com/HDFGroup/datacontainer/blob/master/docs/osdc_cluster.md) under docs.

**Comment by hyoklee** [comment]
This happens when you run  ```rc=Client()``` on engine instance.

**Comment by ajelenak-thg** [comment]
I have never had this problem using the same instruction.

**Comment by jreadey** [comment]
@hyoklee - why are you running Client from the engine node?

**Comment by hyoklee** [comment]
I was curious.

**Comment by jreadey** [comment]
I suspect it is because you don't have the $HOME/.ipython/profile_default/security/ipcontroller-client.json file on the engine instance.
